Nesta versao da pasta jar, temos: uma estrutura de pacotes e uma dsl com essa estrutura. Ela foi criada a partir das seguintes classes: david@linux-touch:~/comdd/ANTLR_Codigos/jar$ jar -cvfm dsl.jar manifest.txt antlr-3.0 classes source Todas as classes e fontes da dsl normal (sem ser em jar), mais todo o antlr Como saída tive: david@linux-touch:~/comdd/ANTLR_Codigos/jar$ java -jar dsl.jar Exception in thread "main" java.lang.NoClassDefFoundError: Test Caused by: java.lang.ClassNotFoundException: Test 	at java.net.URLClassLoader$1.run(URLClassLoader.java:202) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:307) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:248) Could not find the main class: Test. Program will exit.