Gerei o jar a partir de: david@linux-touch:~/comdd/ANTLR_Codigos/jar$ jar -cvfm dsl.jar MANIFEST.MF MyDsl.tokens MyDsl__.g MyDslLexer.class MyDslParser.class Test.class
Como saída obtive:
david@linux-touch:~/comdd/ANTLR_Codigos/jar$ java -jar dsl.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/antlr/runtime/CharStream
Caused by: java.lang.ClassNotFoundException: org.antlr.runtime.CharStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: Test. Program will exit.


Tentativa de solução: inserir a pasta antlr toda dentro do jar